### PR TITLE
feat: config override

### LINKED ISSUE #631: Can't publish a snapshot for commits starting with 0
For example publishing from 0350005612540d8a6a2dc3a316c1fa70cb834086 results in `Error: Version segment starts with 0`

### PR DESCRIPTION
**Pull request by kalinkrustev**
- fixes #631
- implemet mojaloop/project#3936 for some of the charts

What is going on here is that in the values one can specify something like this:
```yaml
configOverride:
  .EVENT_SDKrc:
    # configuration overrides for event sdk
  .CLEDGrc:
    # configuration overrides for central ledger
```
Then these will be volume-mounted as files `.EVENT_SDKrc` and `.CLEDGrc` within the `/opt/app` dir, where they will be processed by the `rc` module.
The configuration properties will work as overrides on top of the `default.json`.
This is a way to apply individual changes to configuration properties in IAC, instead of copying the whole configuration from the `default.json` file.

### CODE REVIEW

**Review by vijayg10 — COMMENTED** [review]
This looks good to me. Do you want to add empty configOverride section with some comments in the values files?

**Comment by kalinkrustev** [comment]
> This looks good to me. Do you want to add empty configOverride section with some comments in the values files?

Added the section in 88aa64e43db06afc332a83cc6ddc13e1d720167d

**Comment by kalinkrustev** [comment]
@elnyry-sam-k are you OK with merging this to master?

There are a lot of changed files, but they all do the same for each chart:

- add templates/config-override.yaml
- mount in in the opt/apt folder

**Review by elnyry-sam-k — APPROVED** [review]
very powerful feature. Thanks @kalinkrustev

**Pull request merged**
