### PR TITLE
feat(mojaloop/#3073): Remove committed code from gh-pages branch

### PR DESCRIPTION
**Pull request by kleyow**
feat(mojaloop/#3073): add code to remove commited code from repo branch - https://github.com/mojaloop/project/issues/3073

### CODE REVIEW

**Comment by kleyow** [comment]
Here is a dry run through of the ci with the changes. Cleaned up my test tags.

https://app.circleci.com/pipelines/github/mojaloop/helm/5093/workflows/e84d5809-38b0-493f-93d0-cdab8b6e59d7/jobs/14977

@mdebarros Ready for a review.

**Comment by elnyry-sam-k** [comment]
looks good to me. Minor comment: the CI steps now have a "checkout" step, which is more "clone" step now..

**Review by mdebarros — APPROVED** [review]
+1

**Comment by mdebarros** [comment]
> looks good to me. Minor comment: the CI steps now have a "checkout" step, which is more "clone" step now; don't think its an issue though

This is correct Sam. The "changed" code is being "checked" out, build and then committed seperately to the gh-pages branch.

**Comment by kleyow** [comment]
@elnyry-sam-k Miguel clarifies the in his comment.

**Pull request merged**
