### PR TITLE
remove erronoeous semicolons from helm repo add

### PR DESCRIPTION
**Pull request by vorburger**
These shouldn't be required, agreed? They don't do much harm either, but for commands on new lines, look unusual and just optically bothered me.

### CODE REVIEW

**Comment by rmothilal** [comment]
@vorburger it’s there if you copy and paste the entire block to separate statements

**Comment by vorburger** [comment]
> @vorburger it’s there if you copy and paste the entire block to separate statements

Probably depends a bit on the exact Terminal + Shell one uses, but I can copy and paste the entire block just fine, and it works (it's executed as 3 separate command lines in my Shell). I believe this is the more common case, it's less typical to write it with trailing semicolons if it's on separate lines. It would be different if the README contained it all in 1 line - but it doesn't.

Certainly just a minor point though.

**Review by rmothilal — DISMISSED** [review]
Happy

**Review by mdebarros — APPROVED** [review]
+1

**Pull request merged**
