### PR TITLE
update ingress to v1 and to helm api v2

### PR DESCRIPTION
**Pull request by tdaly61**
**Update the Chart.yaml's and standardise all charts to helm v3 (API v2)**
- move any dependencies in the requirements.yaml to Charts.yaml
- update the apiVersion for helm in all the Charts.yaml to 2.0
- add the common dependency to each chart that already has an ingress
- remove all requirements.lock (though they should not appear in the repo)
- update maintainers in chart.yaml to include tomd@crosslaketech

**Update the ingress and networking API to v1 and standardise where possible **
- if the chart has an ingress and it is not on the exclusion list (see below) =>   the ingress is updated to be a clone of the  bitnami example (a version of what already exists in the charts repo)
- updates the values files for the new ingress settings
--  ensure the updated values files have the correct hostname for the ingress
--  checks for paths and extra paths correctly allowed for (i.e. all charts with extraPaths or extraHosts are on e
--  ensure the updated values files have the correct port number for the ingress 
-- update config/default.json files for values.ingress.api.host or similar to use .Values.ingress.hostname 
-  _helper.tpl's updated to use correct ingress APIs and remove ingress version logic

Exclusion list of charts
i.e. these charts are not yet standardised to the new ingress modeled on the bitnami example : 
Any existing ingress in these charts has been updated "in place" rather than replaced with the newer standardised bitnami modeled chart. 
So the ingress.yaml, config/*json, _helper.tpls , values.yaml files etc have been updated to use the latest ingress but they remain non-standard compared to the rest of the code-base.  
        "finance-portal-settlement-management",
        "finance-portal",
        "thirdparty",
        "thirdparty/chart-tp-api-svc",
        "thirdparty/chart-consent-oracle",
        "thirdparty/chart-auth-svc",
        "mojaloop-simulator",
        "keycloak",
        "monitoring",
        "monitoring/promfana",
        "monitoring/elk",
        "ml-testing-toolkit/chart-keycloak",
        "ml-testing-toolkit/chart-backend",
        "ml-testing-toolkit/chart-frontend",
        "ml-testing-toolkit/chart-connection-manager-backend",
        "ml-testing-toolkit/chart-connection-manager-frontend"

### CODE REVIEW

**Review by mdebarros — COMMENTED** [review]
Hey @tdaly61 , 

Thanks for PR. Much appreciated!

I will review it in detail, but just off the top of my head, here are some issues I picked up by glancing through the changes:
1. No chart version have been bumped
2. There are some config values that are no longer “readable” (i.e. protocol versions)
3. I see the existing templates  <chart-name>.apiVersion.Ingress for  _helpers.tpl was updated…and I suspected this is/was not needed since we are using the common library instead?


In addition, take note of the CI failures.

**Comment by tdaly61** [comment]
hi @mdebarros , so I have modified the charts to take care of the 3 items you have posted in your review and a coupe of other minor formatting issues.  I am noticing that some helm tests fail (but less that reported as  failed in the announcements channel yesterday ). Do you have other changes for me from your review yet ?  Have you managed to test yet in k8s version 1.24.

Anyhow I will push my latest changes today or tomorrow thanks and cheers  Tom

**Comment by elnyry-sam-k** [comment]
@tdaly61 , the PRs need an approval to be merged.. I'm not seeing any approval by codeowners or otherwise here..

Please do not merge PRs without at least one approval..

**Comment by elnyry-sam-k** [comment]
Not just the changes, there are CI steps failing here as well

**Comment by elnyry-sam-k** [comment]
we'll need to revert this..

**Pull request merged**
